/*
 * include/linux/six_disk_layout.h
 *
 * AUTO-GENERATED by port/image/mksingledisk.py from port/image/disk_layout.json.
 * DO NOT EDIT MANUALLY -- edit port/image/disk_layout.json instead.
 *
 * Unified Single Multi-Partition Host Disk Image Layout for SIX (239 MiB):
 *   LBA 0           (0 .. 511):          Protective MBR (0xEE)
 *   LBA 1           (512 .. 1023):       Primary GPT Header ("EFI PART")
 *   LBA 2..33       (1024 .. 17407):     Primary GPT Partition Entries (1..11)
 *   Partition 1     (  1 MiB ..  51 MiB,  50 MiB): root           (/dev/hda)
 *   Partition 2     ( 51 MiB .. 101 MiB,  50 MiB): aux_storage-1  (/dev/hdb)
 *   Partition 3     (101 MiB .. 151 MiB,  50 MiB): aux_storage-2  (/dev/hdc)
 *   Partition 4     (151 MiB .. 207 MiB,  56 MiB): bin_storage    (/dev/hdd)
 *   Partition 5     (207 MiB .. 223 MiB,  16 MiB): nvme0n1        (/dev/nvme0n1)
 *   Partition 6     (223 MiB .. 228 MiB,   5 MiB): ufs0           (/dev/ufsa)
 *   Partition 7     (228 MiB .. 230 MiB,   2 MiB): usb_ext2       (/dev/sda)
 *   Partition 8     (230 MiB .. 232 MiB,   2 MiB): usb_ext4       (/dev/sda)
 *   Partition 9     (232 MiB .. 234 MiB,   2 MiB): usb_erofs      (/dev/sda)
 *   Partition 10    (234 MiB .. 236 MiB,   2 MiB): usb_ntfs       (/dev/sda)
 *   Partition 11    (236 MiB .. 238 MiB,   2 MiB): usb_crypt      (/dev/sda)
 *   Footer          (238 MiB .. 239 MiB,   1 MiB): Backup GPT Entries & Header
 */
#ifndef _LINUX_SIX_DISK_LAYOUT_H
#define _LINUX_SIX_DISK_LAYOUT_H

#define SIX_MIB_BYTES			(1024UL * 1024UL)
#define SIX_MIB_SECTORS			(2048UL)

#define SIX_SINGLE_DISK_TOTAL_MIB	239UL
#define SIX_SINGLE_DISK_TOTAL_BYTES	(SIX_SINGLE_DISK_TOTAL_MIB * SIX_MIB_BYTES)
#define SIX_SINGLE_DISK_TOTAL_SECTORS	(SIX_SINGLE_DISK_TOTAL_MIB * SIX_MIB_SECTORS)

/* Any backing file >= 180 MiB is treated as a unified multi-partition image */
#define SIX_SINGLE_DISK_MIN_BYTES	(180UL * SIX_MIB_BYTES)

#define SIX_GPT_MAX_PARTITIONS		16

/* Partition 1: root (/dev/hda) - 50 MiB at 1 MiB */
#define SIX_PART_ROOT_NUM		1
#define SIX_PART_ROOT_LABEL		"root"
#define SIX_PART_ROOT_OFFSET		(1UL * SIX_MIB_BYTES)
#define SIX_PART_ROOT_BYTES		(50UL * SIX_MIB_BYTES)
#define SIX_PART_ROOT_SECTORS	(50UL * SIX_MIB_SECTORS)

/* Partition 2: aux_storage-1 (/dev/hdb) - 50 MiB at 51 MiB */
#define SIX_PART_AUX1_NUM		2
#define SIX_PART_AUX1_LABEL		"aux_storage-1"
#define SIX_PART_AUX1_OFFSET		(51UL * SIX_MIB_BYTES)
#define SIX_PART_AUX1_BYTES		(50UL * SIX_MIB_BYTES)
#define SIX_PART_AUX1_SECTORS	(50UL * SIX_MIB_SECTORS)

/* Partition 3: aux_storage-2 (/dev/hdc) - 50 MiB at 101 MiB */
#define SIX_PART_AUX2_NUM		3
#define SIX_PART_AUX2_LABEL		"aux_storage-2"
#define SIX_PART_AUX2_OFFSET		(101UL * SIX_MIB_BYTES)
#define SIX_PART_AUX2_BYTES		(50UL * SIX_MIB_BYTES)
#define SIX_PART_AUX2_SECTORS	(50UL * SIX_MIB_SECTORS)

/* Partition 4: bin_storage (/dev/hdd) - 56 MiB at 151 MiB */
#define SIX_PART_BIN_NUM		4
#define SIX_PART_BIN_LABEL		"bin_storage"
#define SIX_PART_BIN_OFFSET		(151UL * SIX_MIB_BYTES)
#define SIX_PART_BIN_BYTES		(56UL * SIX_MIB_BYTES)
#define SIX_PART_BIN_SECTORS	(56UL * SIX_MIB_SECTORS)

/* Partition 5: nvme0n1 (/dev/nvme0n1) - 16 MiB at 207 MiB */
#define SIX_PART_NVME_NUM		5
#define SIX_PART_NVME_LABEL		"nvme0n1"
#define SIX_PART_NVME_OFFSET		(207UL * SIX_MIB_BYTES)
#define SIX_PART_NVME_BYTES		(16UL * SIX_MIB_BYTES)
#define SIX_PART_NVME_SECTORS	(16UL * SIX_MIB_SECTORS)

/* Partition 6: ufs0 (/dev/ufsa) - 5 MiB at 223 MiB */
#define SIX_PART_UFS_NUM		6
#define SIX_PART_UFS_LABEL		"ufs0"
#define SIX_PART_UFS_OFFSET		(223UL * SIX_MIB_BYTES)
#define SIX_PART_UFS_BYTES		(5UL * SIX_MIB_BYTES)
#define SIX_PART_UFS_SECTORS	(5UL * SIX_MIB_SECTORS)

/* Partition 7: usb_ext2 (/dev/sda) - 2 MiB at 228 MiB */
#define SIX_PART_USB_EXT2_NUM		7
#define SIX_PART_USB_EXT2_LABEL		"usb_ext2"
#define SIX_PART_USB_EXT2_OFFSET		(228UL * SIX_MIB_BYTES)
#define SIX_PART_USB_EXT2_BYTES		(2UL * SIX_MIB_BYTES)
#define SIX_PART_USB_EXT2_SECTORS	(2UL * SIX_MIB_SECTORS)

/* Partition 8: usb_ext4 (/dev/sda) - 2 MiB at 230 MiB */
#define SIX_PART_USB_EXT4_NUM		8
#define SIX_PART_USB_EXT4_LABEL		"usb_ext4"
#define SIX_PART_USB_EXT4_OFFSET		(230UL * SIX_MIB_BYTES)
#define SIX_PART_USB_EXT4_BYTES		(2UL * SIX_MIB_BYTES)
#define SIX_PART_USB_EXT4_SECTORS	(2UL * SIX_MIB_SECTORS)

/* Partition 9: usb_erofs (/dev/sda) - 2 MiB at 232 MiB */
#define SIX_PART_USB_EROFS_NUM		9
#define SIX_PART_USB_EROFS_LABEL		"usb_erofs"
#define SIX_PART_USB_EROFS_OFFSET		(232UL * SIX_MIB_BYTES)
#define SIX_PART_USB_EROFS_BYTES		(2UL * SIX_MIB_BYTES)
#define SIX_PART_USB_EROFS_SECTORS	(2UL * SIX_MIB_SECTORS)

/* Partition 10: usb_ntfs (/dev/sda) - 2 MiB at 234 MiB */
#define SIX_PART_USB_NTFS_NUM		10
#define SIX_PART_USB_NTFS_LABEL		"usb_ntfs"
#define SIX_PART_USB_NTFS_OFFSET		(234UL * SIX_MIB_BYTES)
#define SIX_PART_USB_NTFS_BYTES		(2UL * SIX_MIB_BYTES)
#define SIX_PART_USB_NTFS_SECTORS	(2UL * SIX_MIB_SECTORS)

/* Partition 11: usb_crypt (/dev/sda) - 2 MiB at 236 MiB */
#define SIX_PART_USB_CRYPT_NUM		11
#define SIX_PART_USB_CRYPT_LABEL		"usb_crypt"
#define SIX_PART_USB_CRYPT_OFFSET		(236UL * SIX_MIB_BYTES)
#define SIX_PART_USB_CRYPT_BYTES		(2UL * SIX_MIB_BYTES)
#define SIX_PART_USB_CRYPT_SECTORS	(2UL * SIX_MIB_SECTORS)

struct six_gpt_part_info {
	int part_num;
	char label[36];
	unsigned long start_lba;
	unsigned long end_lba;
	unsigned long sectors;
	unsigned long offset_bytes;
	unsigned long size_bytes;
};

extern char six_root_disk_path[256];
extern unsigned long six_disk_offset[4];
extern int six_gpt_lookup_part(const char *label, unsigned long *offset_out,
			       unsigned long *bytes_out, int *part_num_out);
extern int six_gpt_get_part_count(void);
extern const struct six_gpt_part_info *six_gpt_get_part_by_index(int idx);

#endif /* _LINUX_SIX_DISK_LAYOUT_H */
