#
# Makefile for the Linux ext4-filesystem routines in SIX.
#

O_TARGET := ext4.o
O_OBJS   := acl.o balloc.o bitmap.o dir.o extents.o file.o fsync.o htree.o \
            ialloc.o inode.o ioctl.o namei.o super.o symlink.o truncate.o
M_OBJS   := $(O_TARGET)

include $(TOPDIR)/Rules.make
