[fwupd]
# SIX Firmware Update Daemon / Manager Configuration
EnabledPlugins=nvme;ufs;scsi
OnlyTrusted=true
AllowEmulation=false
MetadataURI=file:///etc/fwupd/remotes.d/lvfs/metadata.xml
HistoryDatabase=/var/lib/fwupd/history.db
